============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
wandb: Currently logged in as: jessewiers (jessewiers-university-of-amsterdam). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.4
wandb: Run data is saved locally in /gpfs/home4/jwiers/deeprisk/new_codebase/enf-biobank/wandb/run-20250410_162434-jg62sa90
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run 512l_64d_3d
wandb: ‚≠êÔ∏è View project at https://wandb.ai/jessewiers-university-of-amsterdam/Recon2D_10-04_investigating_z%3D1_2d_3d
wandb: üöÄ View run at https://wandb.ai/jessewiers-university-of-amsterdam/Recon2D_10-04_investigating_z%3D1_2d_3d/runs/jg62sa90
INFO:2025-04-10 16:24:49,502:jax._src.xla_bridge:945: Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0410 16:24:49.502237 23291469103616 xla_bridge.py:945] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO:2025-04-10 16:24:49,503:jax._src.xla_bridge:945: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
I0410 16:24:49.503287 23291469103616 xla_bridge.py:945] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
I0410 16:25:39.679759 23291469103616 biobank_reconstruction_3d.py:283] RECON ep 0 / step 200 || mse: 35187618480128.0
I0410 16:26:13.822029 23291469103616 biobank_reconstruction_3d.py:283] RECON ep 0 / step 400 || mse: 44404056260608.0
I0410 16:26:47.972034 23291469103616 biobank_reconstruction_3d.py:283] RECON ep 0 / step 600 || mse: 41866326179840.0
I0410 16:27:22.132912 23291469103616 biobank_reconstruction_3d.py:283] RECON ep 0 / step 800 || mse: 68471316545536.0
I0410 16:27:56.297335 23291469103616 biobank_reconstruction_3d.py:283] RECON ep 0 / step 1000 || mse: 24546170109952.0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 11120886 ON gcn117 CANCELLED AT 2025-04-10T16:28:29 ***
slurmstepd: error: *** STEP 11120886.0 ON gcn117 CANCELLED AT 2025-04-10T16:28:29 ***
